services:
    ctf:
        restart: always
        build:
            context: .
            dockerfile: ./Dockerfile
        read_only: false
        tmpfs: 
          - /tmp
        ports:
            - '31415:31415'
